### ISSUE TITLE
Refactor `DockerManager.client` to `DockerManager.docker`

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-node#12]

**Comment by frankcorneliusmartin** [comment]
@mellesies The external module `docker` carries the same name. Even though it is possible, I am not sure if I am really happy with refactoring this to `DockerManager.docker`. 

Maybe `docker_client`? What is bothering you about the `client` part?

**Comment by mellesies** [comment]
In my opinion `client` is too generic and can be easily misinterpreted to be the client to the server or socketIO or ... 
I don't think using `DockerManager.docker` (which translates to `self.docker` in the class' code) runs the risk of confusing it with the module, but I can live with `docker_client` too.

**Comment by frankcorneliusmartin** [comment]
refactored to `Dockermanager.docker` merged in 1.1.0
