### ISSUE TITLE
Support for server-based databases as data store for vantage6 node

### ISSUE THREAD

**Issue by svenvanderburg** [IKNL/vantage6-node#22]
It seems the node setup only supports file-based storage in the form of CSV files for now. IMO vantage6 would become way more scalable and more broadly applicable if it would support server-based databases (such as `MS-SQL Server` and `neo4j`).

**Comment by svenvanderburg** [comment]
After discussion with @jvsoest : It should be possible by taking the file path  to fill in the URL of the sparql endpoint. This URL is retrievable by the algorithm, and can be used to trigger the query. The only thing to keep in mind is that the URL you're providing is reachable from within the docker container. Using something like http://localhost:7200/repositories/test is not going to work, as localhost is within the algorithm docker container. So you need an internal host name or IP address which is reachable for the algorithm container.

**Comment by svenvanderburg** [comment]
@mellesies also mentioned the network traffic for algorithm containers is limited, so you'd have to whitelist the database URI somehow.

**Comment by dsmits** [comment]
Adding the database to the algorithm container sounds doable. If I understand it correctly the algorithm  network is called ` vantage6-NODE_CONTAINER-user-net` (fill in your node container name)

**Comment by svenvanderburg** [comment]
Prefixing `DATABASE_URI` with `data_folder` doesn't really help for a database-endpoint URI (see [code])(https://github.com/IKNL/vantage6-node/blob/116f2a856f2c11d99eb18948f543929e4dc68d3e/vantage6/node/docker_manager.py#L313), I'm circumventing it, but would be nice to change this if you want to fully support database endpoints.

**Comment by frankcorneliusmartin** [comment]
Somehow the node manager needs to be aware if we are dealing with a filebased database or not. Not sure if this belongs in the DockerManager class...

**Comment by mahletA** [comment]
> Adding the database to the algorithm container sounds doable. If I understand it correctly the algorithm network is called ` vantage6-NODE_CONTAINER-user-net` (fill in your node container name)

is it currently possible to whitelist a url in the container network? So the container can be able to reach some endpoints other than the node?

**Comment by frankcorneliusmartin** [comment]
> > Adding the database to the algorithm container sounds doable. If I understand it correctly the algorithm network is called ` vantage6-NODE_CONTAINER-user-net` (fill in your node container name)
> 
> is it currently possible to whitelist a url in the container network? So the container can be able to reach some endpoints other than the node?

No that is currently not possible, the algorithm container can only reach services in the internal network. To communicate with the central server a local proxy is in place, see https://github.com/IKNL/vantage6-node/blob/master/vantage6/node/proxy_server.py

This proxy could be extended using a whitelist. This has been planned yet.

**Comment by frankcorneliusmartin** [comment]
Whitelist feature in a separate issue: #34 . 

Some fixes to allow other data sources than CSV:

`vantage6 CLI`

- https://github.com/IKNL/vantage6/commit/df91e573e587dd7b48593a972ae0a1dcc960bba4
- https://github.com/IKNL/vantage6/commit/3b8785bfdc64778e4943827bebaaaa9156ce690c

`vantage6 node`

- 4ea6c1824b19649a917dfa5fe82eea5ce4b04937
- 548891149e3181c5f6307188c66fda2ad767974a

To allow the current (and older versions) to reach an external source outside of the docker network, you need to set `internal=True` when creating the network: 
https://github.com/IKNL/vantage6-node/blob/3dcc8c389a21504a0768a76f65082f78ac297885/vantage6/node/docker_manager.py#L141

Untill the whitelist (#34) feature is available, the best solution would be to attach the service to the docker network as @dsmits suggested.
