### ISSUE TITLE
Add option to vnode: --version 

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-node#3]
Having the commands `vnode --version` and `vnode-local --version` would be helpful for providing support.

### vnode-local
- for a regular installation, `vnode.__version__` should be returned. 
- for an editable installation, `vnode.__version__` should be returned together with the (short) hash of the current commit (if available) and the current branch (if available).

### vnode
- see above; _and_
- the output for `vnode-local`, run within docker, should be added.

**Comment by intGRen** [comment]
Fixed in: d939b0c395b02de9c680f7ca107da624a718cd2f and 16b4d25de6de5fdf5ccc6092757716e15df4debf
