### ISSUE TITLE
Task, log and datadir are not setable in the config file

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-node#5]
- [x] non-dockerized version
- [x] dockerized version (mounts)
- [ ] update documentation
- [ ] check file permissions

**Comment by frankcorneliusmartin** [comment]
@mellesies What would you expect in the case of the Dockerized version? 
I think I would prefer to have mounts to these files?

**Comment by mellesies** [comment]
I would expect the locations in the config file to point to locations on the host machine. (As an end user I don't care where in the docker container these files are stored, but I do care about persistence).

So using mounts sounds sensible.

**Comment by frankcorneliusmartin** [comment]
@mellesies The datadir and task dir are the same in the current version. Do we need them to be separate folders?

**Comment by frankcorneliusmartin** [comment]
Taskdir cannot be mounted as this is stored in a docker volume. On windows it is not possible to create a volume with a mount to the host (to the mobyVM is possible). On MacOS/Linux this should probably work (https://docs.docker.com/engine/reference/commandline/volume_create/).

Even if you manage to get this working on windows, it will be a somewhat poor experience as once the volume is created you no longer can change the task dir in the settings file (or you have to remove the volume completely...)

Any thoughts on this?

**Comment by frankcorneliusmartin** [comment]
@mellesies Yes I agree. I created a seperate issue for this: #23

**Comment by frankcorneliusmartin** [comment]
Partially implemented (see comments above and #23) and merged in 1.1.0
