### ISSUE TITLE
Different labels for the same CSV results in not copying the second

### ISSUE THREAD

**Issue by anjavangestel** [IKNL/vantage6-node#50]
When using the multi-database option in the node configuration file errors occur when the same .csv is used for different labels.

![image](https://user-images.githubusercontent.com/47362091/144237740-61728180-24ba-4950-a5df-b109c61b0bb6.png)

![image](https://user-images.githubusercontent.com/47362091/144237763-d936c848-303c-4be4-a495-73bfd2e5c34b.png)

In the example for the screenshots we have 8 labels, and 7 csv files. (Hypo AND MajorS labels point both to MajorS csv)
- it appears that config=dict_keys([...]) indeed contains 8 keys. (screenshot 1)
- 7 csv files get copied. (screenshot 1)
- somehow GROUPED_H&N_HYPO_DATABASE_URI points to grouped_H&N_Hypo.csv (which does not exist). (screenshot 2)
- also another variable DATABASE_URI exists which points to a weird path: /mnt/data//mnt/grouped_H&N_Hypo.csv. (screenshot 2)
- when an algorithm is executed for the label Hypo you now get the error that hypo.csv cannot be found. (screenshot 2)

**Comment by frankcorneliusmartin** [comment]
- [ ] harukas - https://github.com/IKNL/vantage6/commit/c5376ace7f093a5c6d365b29e40081ee6214670b
- [ ] petronas
