### ISSUE TITLE
Muti-database support

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-node#6]
It is possible to specify multiple databases in the configuration files. It is however currently not possible to access any other database then `default`.

**Comment by frankcorneliusmartin** [comment]
implemented in: 34c9b089eb90e3eeff2904ff11a668ddff9b51b4

**Comment by frankcorneliusmartin** [comment]
Merge together:
* https://github.com/IKNL/vantage6/tree/feature/multi-database
* https://github.com/IKNL/vantage6-node/tree/feature/multi-database-dev3

**Comment by bartvanb** [comment]
not functional yet for `vnode-local`

**Comment by frankcorneliusmartin** [comment]
I also get errors when using `vnode`: 

`2022-01-27 15:50:14 - task_manager   - ERROR    - '' database missing! This could crash legacy algorithms`

**Comment by bartvanb** [comment]
I just solved two issues. Now, algorithms can be run again with the *legacy* version in both `vnode` and `vnode-local`. I have not yet tested with multiple-databases so I'm not closing this yet. @frankcorneliusmartin can you verify that it works with multiple databases?

**Comment by frankcorneliusmartin** [comment]
Checked with the feature tester. Both `vnode` and `vnode-local` did work.
